# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aigit < Formula
  desc "Git but for AI agents."
  homepage "https://github.com/ReyNeill/aigit"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ReyNeill/aigit/releases/download/v0.1.4/aigit_0.1.4_darwin_amd64.tar.gz"
      sha256 "2ab2190ceb40adbf4e4688c381665c684aced6f71c2602350d6b74957f079815"

      def install
        bin.install "aigit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ReyNeill/aigit/releases/download/v0.1.4/aigit_0.1.4_darwin_arm64.tar.gz"
      sha256 "046114481b2e574bd4bf9da122fa9724cb53279b9e37c443cbbd5a7e41f0d303"

      def install
        bin.install "aigit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ReyNeill/aigit/releases/download/v0.1.4/aigit_0.1.4_linux_amd64.tar.gz"
      sha256 "5c030fcdcd9e1f8315d7613dc8086b47ba4bc4ce8f6cccd1752afb87f9f5b056"
      def install
        bin.install "aigit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ReyNeill/aigit/releases/download/v0.1.4/aigit_0.1.4_linux_arm64.tar.gz"
      sha256 "63ef0c08d1ca14ab405222905acc88b58bd475b141007c1315dd486c9de1fdd1"
      def install
        bin.install "aigit"
      end
    end
  end

  test do
    system "#{bin}/aigit", "status"
  end
end
